/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import DAO.KhachHangDAO;
import DAO.KhuyenMaiDAO;
import Entity.KhachHang;
import Entity.KhuyenMai;
import java.awt.Container;
import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import utils.Auth;
import utils.MsgBox;
import utils.XDate;
import utils.XImage;

/**
 *
 * @author Quan
 */
public class KhuyenMaiJInternalFrame extends javax.swing.JInternalFrame {

    KhuyenMaiDAO dao = new KhuyenMaiDAO();
    JFileChooser fileChooser = new JFileChooser();
    int row = -1;
    KhachHangDAO daokh = new KhachHangDAO();

    public KhuyenMaiJInternalFrame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        fillToTable();
        lblHinh.setToolTipText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSale1 = new javax.swing.JLabel();
        lblQuanLyKhuyenMai = new javax.swing.JLabel();
        lblSale2 = new javax.swing.JLabel();
        txtTenKhuyenMai = new javax.swing.JTextField();
        txtMaKhuyenMai = new javax.swing.JTextField();
        lblMKM = new javax.swing.JLabel();
        lblTKM = new javax.swing.JLabel();
        lblGKM1 = new javax.swing.JLabel();
        txtNgayKetThuc = new javax.swing.JTextField();
        lblGKM = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        lblGKM2 = new javax.swing.JLabel();
        txtGiakhuyenMai = new javax.swing.JTextField();
        lblThem = new javax.swing.JLabel();
        lblMoi = new javax.swing.JLabel();
        lblSua = new javax.swing.JLabel();
        lblXoa = new javax.swing.JLabel();

        lblSale1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale.png"))); // NOI18N

        lblQuanLyKhuyenMai.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblQuanLyKhuyenMai.setForeground(new java.awt.Color(0, 204, 51));
        lblQuanLyKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyKhuyenMai.setText("QUẢN LÝ KHUYẾN MÃI");

        lblSale2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale.png"))); // NOI18N

        lblMKM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMKM.setForeground(new java.awt.Color(0, 153, 51));
        lblMKM.setText("Mã khuyến Mãi");

        lblTKM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTKM.setForeground(new java.awt.Color(0, 153, 51));
        lblTKM.setText("Tên khuyến mãi");

        lblGKM1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGKM1.setForeground(new java.awt.Color(0, 153, 51));
        lblGKM1.setText("Ngày kết thúc");

        lblGKM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGKM.setForeground(new java.awt.Color(0, 153, 51));
        lblGKM.setText("Ngày bắt đầu");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khuyến Mãi", "Tên Khuyến Mãi", "Ngày bắt đầu", "Ngày kết thúc", "Hình", "Khuyến Mãi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);
        if (tblKhuyenMai.getColumnModel().getColumnCount() > 0) {
            tblKhuyenMai.getColumnModel().getColumn(4).setMinWidth(70);
            tblKhuyenMai.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        lblGKM2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGKM2.setForeground(new java.awt.Color(0, 153, 51));
        lblGKM2.setText("Giá Khuyến Mãi");

        lblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/them_defaul.png"))); // NOI18N
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemMouseExited(evt);
            }
        });

        lblMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moi_defaul.png"))); // NOI18N
        lblMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMoiMouseExited(evt);
            }
        });

        lblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sua_defaul.png"))); // NOI18N
        lblSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuaMouseExited(evt);
            }
        });

        lblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xoa_defaul.png"))); // NOI18N
        lblXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXoaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(txtTenKhuyenMai))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblGKM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGKM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGKM2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGiakhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMoi)
                                            .addComponent(lblSua)))
                                    .addComponent(lblXoa)
                                    .addComponent(lblThem)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(lblSale1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSale2)))
                .addGap(113, 247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSale1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSale2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMKM)
                            .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTKM)
                            .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGKM)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGKM1)
                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGKM2)
                            .addComponent(txtGiakhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMoi)
                            .addComponent(lblThem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSua)
                            .addComponent(lblXoa)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        GetHinhAnh();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        if (evt.getClickCount() == 1) {
            row = tblKhuyenMai.getSelectedRow();
            edit();
        }
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void lblThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseEntered
        lblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/them_hover.png")));
    }//GEN-LAST:event_lblThemMouseEntered

    private void lblThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseExited
        lblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/them_defaul.png")));
    }//GEN-LAST:event_lblThemMouseExited

    private void lblThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseClicked
        if (evt.getClickCount() == 2 || evt.getClickCount() == 1) {
            add();
        }
    }//GEN-LAST:event_lblThemMouseClicked

    private void lblMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoiMouseClicked
        if (evt.getClickCount() == 2 || evt.getClickCount() == 1) {
            clear();
        }
    }//GEN-LAST:event_lblMoiMouseClicked

    private void lblMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoiMouseEntered
        lblMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moi_hover.png")));
    }//GEN-LAST:event_lblMoiMouseEntered

    private void lblMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoiMouseExited
        lblMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moi_defaul.png")));
    }//GEN-LAST:event_lblMoiMouseExited

    private void lblSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaMouseClicked
        if (evt.getClickCount() == 2 || evt.getClickCount() == 1) {
            update();
        }
    }//GEN-LAST:event_lblSuaMouseClicked

    private void lblSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaMouseEntered
        lblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sua_hover.png")));
    }//GEN-LAST:event_lblSuaMouseEntered

    private void lblSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaMouseExited
        lblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sua_defaul.png")));
    }//GEN-LAST:event_lblSuaMouseExited

    private void lblXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaMouseClicked
        if (evt.getClickCount() == 2 || evt.getClickCount() == 1) {
            delete();
        }
    }//GEN-LAST:event_lblXoaMouseClicked

    private void lblXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaMouseEntered
        lblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xoa_hover.png")));
    }//GEN-LAST:event_lblXoaMouseEntered

    private void lblXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaMouseExited
        lblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xoa_defaul.png")));
    }//GEN-LAST:event_lblXoaMouseExited

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblKhuyenMai.getModel();
        model.setRowCount(0);
        List<KhuyenMai> list = dao.selectAll();
        for (KhuyenMai km : list) {
            Object[] row = {km.getMaKM(), km.getTenKM(), km.getNgayBD(),
                km.getNgayKT(), km.getHinh(), km.getGiaKhuyenMai()};
            model.addRow(row);
        }
    }

    public KhuyenMai GetForm() {
        KhuyenMai km = new KhuyenMai();
        km.setMaKM(txtMaKhuyenMai.getText());
        km.setTenKM(txtTenKhuyenMai.getText());
        km.setNgayBD(txtNgayBatDau.getText());
        km.setNgayKT(txtNgayKetThuc.getText());
        km.setHinh(lblHinh.getToolTipText());
        km.setGiaKhuyenMai(txtGiakhuyenMai.getText());
        return km;
    }

    void GetHinhAnh() {
        int width = lblHinh.getWidth();
        int height = lblHinh.getHeight();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        File file = fileChooser.getSelectedFile();
        XImage.save2(file);
        XImage.save(file);
        ImageIcon icon = new ImageIcon(XImage.read(file.getName()).getImage().getScaledInstance(width, height, 0));
        lblHinh.setIcon(icon);
        lblHinh.setToolTipText(file.getName());
    }

    public void add() {
//        KhuyenMai km = new KhuyenMai();
        if (valueDate()) {
            KhuyenMai km = GetForm();
            try {
                dao.insert(km);
                this.fillToTable();
                guiemailkh();
                this.clear();
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                if (km.getMaKM().equalsIgnoreCase(txtMaKhuyenMai.getText())) {
                    MsgBox.alert(this, "Mã khuyến mãi đã tồn tại!");
                } else {
                    MsgBox.alert(this, "Thêm mới thất bại!");
                }
            }
        }
    }

    public void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa món ăn");
        } else {
            String message = "Bạn có chắc muốn xóa ? ";
            String title = "Xác nhận xóa khuyến mãi";
            if (checkSelect("Xóa")) {
                int check = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION) {
                    try {
                        String maKM = txtMaKhuyenMai.getText();
                        dao.delete(maKM);
                        MsgBox.alert(this, "Xóa thành công !");
                        clear();
                        fillToTable();
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại !");
                        throw new RuntimeException(e);
                    }
                }
            }
        }
    }

    void setForm(KhuyenMai km) {
        txtTenKhuyenMai.setText(km.getTenKM());
        txtMaKhuyenMai.setText(km.getMaKM());
        txtNgayBatDau.setText(km.getNgayBD());
        txtNgayKetThuc.setText(km.getNgayKT());
        txtGiakhuyenMai.setText(km.getGiaKhuyenMai());

        int with = lblHinh.getWidth();
        int height = lblHinh.getHeight();
        if (km.getHinh() == null) {
            lblHinh.setIcon(null);
        } else {
            ImageIcon icon = new ImageIcon(XImage.read(km.getHinh()).getImage().getScaledInstance(with, height, 0));
            lblHinh.setIcon(icon);
            lblHinh.setToolTipText(km.getHinh());
        }
    }

    void edit() {
        String maKM = (String) tblKhuyenMai.getValueAt(this.row, 0);
        KhuyenMai km = dao.selectByID(maKM);
        this.setForm(km);
        txtMaKhuyenMai.setEnabled(false);
        lblThem.setEnabled(false);
    }

    public void clear() {
        txtMaKhuyenMai.setText("");
        txtTenKhuyenMai.setText("");
        txtNgayBatDau.setText("");
        txtNgayKetThuc.setText("");
        lblHinh.setIcon(null);
        lblHinh.setToolTipText("");
        txtGiakhuyenMai.setText("");
        txtMaKhuyenMai.setEnabled(true);
        lblThem.setEnabled(true);
    }

    public void update() {
        KhuyenMai km = GetForm();
        if (checkSelect("Sửa")) {
            if (valueDate()) {
                try {
                    dao.update(km);
                    this.fillToTable();
                    this.clear();
                    MsgBox.alert(this, "Cập nhật thành công !");
                } catch (Exception e) {
                    MsgBox.alert(this, "Cập nhật thất bại!");
                    throw new RuntimeException(e);
                }
            }
        }
    }

    public boolean valueDate() {
        if (txtMaKhuyenMai.getText().isEmpty() || txtNgayBatDau.getText().isEmpty()
                || txtNgayKetThuc.getText().isEmpty() || txtTenKhuyenMai.getText().isEmpty()
                || txtGiakhuyenMai.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ thông tin!");
            return false;
        } else if (lblHinh.getToolTipText().equals("") || lblHinh.equals(null)) {
            MsgBox.alert(this, "Bạn chưa chọn hình khuyến mãi!");
            return false;
        } else {
            try {
                int number = Integer.parseInt(txtGiakhuyenMai.getText());
            } catch (NumberFormatException e) {
                MsgBox.alert(this, "Giá khuyến mãi phải là số!");
                return false;
            }
            return true;
        }
    }

    public boolean checkSelect(String doiTuong) {
        if (tblKhuyenMai.getSelectedRow() < 0) {
            MsgBox.alert(this, "Bạn chưa chọn khuyến mãi cấn " + doiTuong + "!");
            return false;
        } else {
            return true;
        }
    }

    void guiemailkh() {
        List<KhachHang> list = daokh.selectAll();
        for (KhachHang khachHang : list) {
            guiEmail(khachHang.getEmail());
        }
    }

    void guiEmail(String email) {
        File file1 = fileChooser.getSelectedFile();
        String ngay = txtNgayBatDau.getText();
        String[] ngaybd = ngay.split("-");
        String a = txtNgayKetThuc.getText();
        String[] ngaykt = a.split("-");
        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", 587);
        String senderEmail = "vihnhps24408@fpt.edu.vn";
        String toEmail = email;
        String subject = "Eatery xin chào quý khách";
        String body = "Hiện nay cửa hàng đang có chưng trình khuyến mãi " + txtGiakhuyenMai.getText() + "% nhân dịp " + txtTenKhuyenMai.getText() + "\n"
                + "Bắt đầu từ ngày " + ngaybd[2] + "-" + ngaybd[1] + "-" + ngaybd[0] + "kết thúc ngày " + ngaykt[2] + "-" + ngaykt[1] + "-" + ngaykt[0];
        String pass1 = "";
        Session s = Session.getInstance(p, new javax.mail.Authenticator() {
            @Override
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(senderEmail, pass1);
            }
        });

        try {
            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(senderEmail));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
            msg.setSubject(subject);
            msg.setText(body);
            MimeBodyPart mbp = new MimeBodyPart();
            mbp.setContent(body, "text/html; charset=utf-8");
            MimeBodyPart filepart = new MimeBodyPart();
            File file = new File("staff\\" + file1.getName());
            FileDataSource fds = new FileDataSource(file);
            filepart.setDataHandler(new DataHandler(fds));
            filepart.setFileName(file.getName());
            MimeMultipart multipart = new MimeMultipart();
            multipart.addBodyPart(mbp);
            multipart.addBodyPart(filepart);
            msg.setContent(multipart);
            Transport.send(msg);
        } catch (MessagingException ex) {
            Logger.getLogger(NhanVienJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGKM;
    private javax.swing.JLabel lblGKM1;
    private javax.swing.JLabel lblGKM2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMKM;
    private javax.swing.JLabel lblMoi;
    private javax.swing.JLabel lblQuanLyKhuyenMai;
    private javax.swing.JLabel lblSale1;
    private javax.swing.JLabel lblSale2;
    private javax.swing.JLabel lblSua;
    private javax.swing.JLabel lblTKM;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblXoa;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtGiakhuyenMai;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtTenKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
